#!/usr/bin/env node
/**
 * Generate GitHub PR comment markdown from CodeCortexLoop report
 *
 * Usage:
 *   node scripts/pr-comment.mjs [report.json] [--baseline-diff=.cortexloop/baseline-diff.json] [--out=.cortexloop/pr-comment.md]
 */

import { existsSync } from 'node:fs';
import { writeFileSync } from 'node:fs';
import {
  CATEGORIES,
  CATEGORY_LABELS,
  DEFAULT_BASELINE_DIFF,
  DEFAULT_PR_COMMENT,
  DEFAULT_REPORT,
  countFindings,
  ensureDirFor,
  getCategoryScores,
  getOverallScore,
  parseArgs,
  readJson,
} from './lib/shared.mjs';

const MARKER = '<!-- cortexloop-report -->';

const { positional, getFlagValue } = parseArgs();
const reportPath = positional[0] || DEFAULT_REPORT;
const baselineDiffPath = getFlagValue('--baseline-diff', DEFAULT_BASELINE_DIFF);
const outPath = getFlagValue('--out', DEFAULT_PR_COMMENT);

if (!existsSync(reportPath)) {
  console.error(`[cortexloop] Report not found: ${reportPath}`);
  process.exit(1);
}

const report = readJson(reportPath);
const overall = getOverallScore(report);
const categories = getCategoryScores(report);
const counts = countFindings(report.findings || []);
const before = report.scores?.before?.overall;
const after = report.scores?.after?.overall;

let baselineSection = '';
if (existsSync(baselineDiffPath)) {
  const diff = readJson(baselineDiffPath);
  baselineSection = `
### Baseline diff

| Bucket | Count |
|--------|------:|
| New | ${diff.summary?.new ?? 0} |
| Fixed | ${diff.summary?.fixed ?? 0} |
| Remaining | ${diff.summary?.remaining ?? 0} |

`;
  if ((diff.new || []).length > 0) {
    baselineSection += '**New findings:**\n';
    for (const f of diff.new.slice(0, 10)) {
      baselineSection += `- \`${f.id}\` **${f.severity}** — ${f.problem} (\`${f.location}\`)\n`;
    }
    if (diff.new.length > 10) baselineSection += `- … and ${diff.new.length - 10} more\n`;
  }
}

const topFindings = (report.findings || [])
  .filter((f) => f.status !== 'fixed' && f.status !== 'suppressed')
  .sort((a, b) => {
    const order = { Critical: 0, High: 1, Medium: 2, Low: 3, Info: 4 };
    return (order[a.severity] ?? 9) - (order[b.severity] ?? 9);
  })
  .slice(0, 8);

let findingsSection = '';
if (topFindings.length) {
  findingsSection = '\n### Top findings\n\n';
  for (const f of topFindings) {
    findingsSection += `- \`${f.id}\` **${f.severity}** · ${f.category} — ${f.problem}\n`;
  }
}

const catLines = CATEGORIES.map((c) => {
  const s = categories[c];
  return `| ${CATEGORY_LABELS[c]} | ${s != null ? Math.round(s) : '—'} |`;
}).join('\n');

const delta =
  before != null && after != null
    ? after - before >= 0
      ? `+${after - before}`
      : `${after - before}`
    : '—';

const md = `${MARKER}
## CodeCortexLoop Report

**Health score:** ${overall != null ? Math.round(overall) : 'n/a'}/100
${before != null ? ` · Before: ${Math.round(before)} → After: ${after != null ? Math.round(after) : 'n/a'} (${delta})` : ''}

| Severity | Count |
|----------|------:|
| Critical | ${counts.Critical} |
| High | ${counts.High} |
| Medium | ${counts.Medium} |
| Low | ${counts.Low} |

### Category scores

| Category | Score |
|----------|------:|
${catLines}

${baselineSection}${findingsSection}
---
📊 [Full dashboard](docs/cortexloop/report.html) · 📄 [report.json](docs/cortexloop/report.json)

*Generated by [CodeCortexLoop](https://github.com/whitequeen306/code-cortex-loop) · preset: ${report.preset || 'unknown'} · scope: ${report.scope || 'recent'}*
`;

ensureDirFor(outPath);
writeFileSync(outPath, md, 'utf8');
console.log(`[cortexloop] PR comment -> ${outPath}`);
